# Generated by Django 5.0.6 on 2025-08-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('qtd_entrada', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('estoque_maximo', models.IntegerField()),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('fora_de_linha', 'Fora de linha'), ('ruptura', 'Ruptura'), ('preco_desatualizado', 'Preço desatualizado'), ('consumo_proprio', 'Consumo próprio'), ('nao_comercializado', 'Não comercializado')], default='ativo', max_length=30)),
                ('ref_fabricante', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('cod_embalagem', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cod_barra', models.CharField(max_length=50)),
                ('data_ultima_compra', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fabricante')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.grupo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.marca')),
            ],
        ),
    ]
