# Generated by Django 5.2.2 on 2025-08-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='BALCÃO', max_length=30)),
                ('formaPagamento', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('descontoDinheiro', models.FloatField(default=0)),
                ('descontoPorcento', models.FloatField(default=0)),
                ('acrescimo', models.FloatField(default=0)),
                ('valorEntregue', models.FloatField()),
                ('troco', models.FloatField(default=0)),
                ('dataHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.vendas')),
            ],
        ),
    ]
